services:
  sekirei-todo-nextjs:
    build:
      dockerfile: ./Dockerfile.nextjs.prod
    #command: bash -c "DEBUG=* pnpm next build && DEBUG=* pnpm next start"
    #command: bash -c "pnpm next build && pnpm next start"
