services:
  sekirei-todo-nextjs:
    command: ['pnpm', 'prod-local']
    depends_on:
      database-preparation:
        condition: service_completed_successfully

  webserver:
    depends_on:
      database-preparation:
        condition: service_completed_successfully

