services:
  sekirei-todo-nextjs:
    image: docker:latest
    container_name: sekirei-todo-dood
    env_file:
      - .env
    environment:
      DOCKER_BUILDKIT: 0
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    tmpfs:
      - /app/.next
    command: >
      docker build
        --network=sekirei-todo-build-network
        -t sekirei-todo-nextjs
        -f Dockerfile.nextjs.prod .
    depends_on:
      database-preparation:
        condition: service_completed_successfully

  database:
    build:
      dockerfile: Dockerfile.mysql
    container_name: sekirei-todo-database
    env_file:
      - .env
    tmpfs:
      - /var/lib/mysql
    environment:
      TZ: 'Asia/Tokyo'
      LANG: 'ja_JP.UTF-8'
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "select 1;"
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  database-preparation:
    image: node:20
    container_name: sekirei-todo-database-preparation
    env_file:
      - .env
    environment:
      NODE_ENV: 'production'
    volumes:
      - ./:/app:ro
    working_dir: /app
    command: >
      bash -c '
        npm install -g pnpm \
        && pnpm drizzle-kit push \
          --dialect=mysql \
          --schema=./src/db/schema.ts \
          --host=$DB_HOST \
          --user=$MYSQL_USER \
          --password=$MYSQL_PASSWORD \
          --database=$MYSQL_DATABASE; \
        pnpx tsx addTestData.ts
      '
    depends_on:
      database:
        condition: service_healthy
    
networks:
  default:
    name: sekirei-todo-build-network

